### ISSUE TITLE
Is there any particular reason why max-results is not an optional parameter?

### ISSUE THREAD

**Issue by sbelak** [weavejester/clucy#12]
I was about to write a patch to use IndexReader.numDocs() [0], but it turns out that would either break backward compatibility or it be half-assed (just a minimal form of `search` without any options), so I am putting it up here for discussion (assuming I haven't missed something blindingly obvious as to why max results needs to be always stringently limited).

[0] http://lucene.apache.org/core/3_6_0/api/all/org/apache/lucene/index/IndexReader.html

**Comment by technomancy** [comment]
I think the Lucene devs got tired of dealing with people doing performance testing badly so they forced this on. You can pass in a ridiculously big number, but that forces you to understand what you're asking for rather than wondering "why is Lucene slow?"
