### ISSUE TITLE
Clojars version 0.3.1 does not have the latest changes for Lucene 4.2

### ISSUE THREAD

**Issue by SergeyDidenko** [weavejester/clucy#17]
The following dependency in project.clj "[clucy "0.3.1"]" leads to getting the old code that does not compile/ work with Lucene 4.2.

For example there is outdated "IndexWriter$MaxFieldLength" and there is no IndexReader.

So I suggest either updating the Clojars or changing Clucy version in project.clj master branch, because it's misleading to have 2 different version here and on Clojars both versioned "0.3.1".

**Comment by weavejester** [comment]
What two different versions? The commit tagged 0.3.1 matches the 0.3.1 jar file in Clojars.

Do you just want a new version released from master?

**Comment by SergeyDidenko** [comment]
Hi James,

my point is that maybe project.clj in master branch should not have the old version - "(defproject clucy "0.3.1"", because there are new changes already.

No, I was just looking at your code to write my own wrappers and was under impression that "0.3.1" works with the latest lucene because the 1) project.clj of master branch has "0.3.1" version 2) the master branch has "update to lucene 4.2.0" commit.

**Comment by weavejester** [comment]
Well, the alternative is to change the project version to a snapshot immediately after cutting a release, but that assumes that you know in advance what the next version is going to be.

Mostly you just need to be aware that the master branch is going to be ahead of what's been released. If you want to know exactly which commit a version was created from, well that's what tags are for.

**Comment by weavejester** [comment]
0.4.0 has been released
